### PR TITLE
Add Support Nested Workspaces and config options to modify the warning text color

### LINKED ISSUE #2: Support Nested Workspaces
The current plugin has a limitation that prevents it from working in workspaces that aren't located in the root of the git repo. Since many projects operate this way I think the plugin could benefit from this being resolved. 

It should be possible to traverse up the directory hierarchy to locate the .git folder or is this known to not work?

### LINKED ISSUE #3: Add a config option to modify the warning text color
Also think it would be useful if there was a configuration option to modify the text color in case it interferes with the uses theme.

### PR DESCRIPTION
**Pull request by ludakhris**
Closes #2 
Closes #3

### CODE REVIEW

**Comment by teledemic** [comment]
Thanks for the PR! Hope to have some time to look at this next week

**Comment by ludakhris** [comment]
Awesome thanks!

**Comment by ludakhris** [comment]
@teledemic just wanted to circle back and see if you had time to review or any questions?

**Review by teledemic — CHANGES_REQUESTED** [review]
Couple small things:
package-lock files should not be gitignored
command name is misspelled as gitbranchwar[m]

**Comment by ludakhris** [comment]
@teledemic made those changes thanks for considering the change!

**Review by teledemic — APPROVED** [review]
Awesome, will publish, thanks for the contribution!

**Pull request merged**
